name: Backend CI/CD

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: eduardomelodeoliveira/gyro-application-prod:backend-v12

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build e Push da imagem Docker
        run: |
          docker build -t $DOCKER_IMAGE ./back-end-gyro
          docker push $DOCKER_IMAGE

      - name: Acessar instância privada via instância pública (SSH)
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.PUBLIC_INSTANCE_IP }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            for HOST in 10.0.1.100 10.0.1.101; do
              echo "▶ Acessando $HOST"

              sudo ssh -o StrictHostKeyChecking=no -i /home/ubuntu/minhassh.pem ubuntu@$HOST "
                cd /home/ubuntu &&
                echo 'Parando e removendo container antigo em $HOST...' &&
                sudo docker-compose down &&
                sudo docker system prune -a --volumes -f &&

                echo 'Atualizando imagem e subindo container em $HOST...' &&
                sudo docker-compose pull &&
                sudo docker-compose up -d --build
              "

              echo "Deploy concluído em $HOST"
            done
